# Generated by Django 5.2.7 on 2025-10-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='category',
            new_name='description',
        ),
    ]
