# Generated by Django 5.2.7 on 2025-12-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
